---
name: Hpa-runners
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build 1
    runs-on: gha-k8s-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
  build-2:
    name: Build 2
    runs-on: gha-k8s-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
  build-3:
    name: Build 3
    runs-on: gha-k8s-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
  build-4:
    name: Build 4
    runs-on: gha-k8s-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
  build-5:
    name: Build 5
    runs-on: gha-k8s-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
