name: Hpa-runners
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: gha-k8s-runner
    strategy:
      matrix:
        build-number: [1, 2, 3, 4,5,6]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        echo "Building docker for build number: ${{ matrix.build-number }}"
        docker build -t test-${{ matrix.build-number }} .
