name: Hpa-runners
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: gha-k8s-runner
    strategy:
      matrix:
        build-number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        echo "Building docker for build number: ${{ matrix.build-number }}"
        docker build -t test-${{ matrix.build-number }} .
